// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// 4613732

const fibs = new Map();
fibs.set(1, 1);
fibs.set(2, 1);

function fibonacci(num) {
  if (!fibs.get(num)) fibs.set(num, fibonacci(num - 1) + fibonacci(num - 2));
  return fibs.get(num);
}

function evenFibSum(limit) {
  let i = 1;
  let total = 0;
  while (true) {
    let val = fibonacci(i);
    if (val >= limit) break;
    if (val % 2 == 0) total += val;
    i++;
  }
  return total;
}

console.log(evenFibSum(4000000));
